# Generated by Django 4.0.6 on 2022-09-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalperson',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical person'},
        ),
        migrations.AlterModelOptions(
            name='historicalsalemonth',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical sale month'},
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalsalemonth',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
