# Generated by Django 4.0.6 on 2022-07-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_personadjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='adjectives',
            field=models.ManyToManyField(to='main.personadjective'),
        ),
    ]
