# Generated by Django 4.0.6 on 2022-08-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_historicalperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalperson',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical person'},
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='adjectives',
            field=models.ManyToManyField(blank=True, to='main.personadjective'),
        ),
        migrations.CreateModel(
            name='PersonAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MVP', 'MVP'), ('MI', 'Most Improved'), ('GOAT', 'GOAT')], max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
        ),
    ]
