# Generated by Django 4.0.6 on 2022-09-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_historicalperson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
