# Generated by Django 4.0.6 on 2022-09-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_day_month_week_year_week_unique_week_month_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='year',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
