# Generated by Django 4.0.6 on 2025-04-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_aux_timeperiods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='month',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='year_num',
            field=models.PositiveSmallIntegerField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['-date'], name='django_aux__date_30db4b_idx'),
        ),
        migrations.AddIndex(
            model_name='month',
            index=models.Index(fields=['-date'], name='django_aux__date_0bcc19_idx'),
        ),
        migrations.AddIndex(
            model_name='month',
            index=models.Index(fields=['year_num', 'month_num'], name='django_aux__year_nu_a6a2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='week',
            index=models.Index(fields=['-date'], name='django_aux__date_75ca1e_idx'),
        ),
        migrations.AddIndex(
            model_name='week',
            index=models.Index(fields=['year_num', 'week_num'], name='django_aux__year_nu_f61330_idx'),
        ),
        migrations.AddIndex(
            model_name='year',
            index=models.Index(fields=['-date'], name='django_aux__date_1c81c7_idx'),
        ),
    ]
