# Generated by Django 4.0.6 on 2026-01-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_aux_timeperiods', '0002_alter_day_options_alter_month_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date_end',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='month',
            name='date_end',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='date_end',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='year',
            name='date_end',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
